/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ClassDados;
import Clases.ClassJugador;
import Util.Cola;
import Util.Lista;
import Util.Pila;
import static Vistas.formInicio.message;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author ARMENI
 */
public class formJuego extends javax.swing.JFrame {

    /**
     * Creates new form formJuego
     */
    
    Lista casillas = new Lista();
    
    Boolean seleccion = true;
    
    ClassJugador jugador1 = new ClassJugador(1,Color.RED,"jugador1");
    ClassJugador jugador2 = new ClassJugador(1,new java.awt.Color(255,204,0),"jugador2");
    ClassJugador jugador3 = new ClassJugador(1,new java.awt.Color(102,204,0),"jugador3");
    ClassJugador jugador4 = new ClassJugador(1,new java.awt.Color(102,0,204),"jugador4");
    
    Cola jugadores = new Cola();
   
    Pila comunal = new Pila();
    Pila suerte = new Pila();

    public formJuego() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jLabelJugador3.setVisible(false);
        jTextFieldDinero3.setVisible(false);
        turno3.setVisible(false);
        jLabelJugador4.setVisible(false);
        jTextFieldDinero4.setVisible(false);
        turno4.setVisible(false);
      
        asignar();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        jPanelCarcel = new javax.swing.JPanel();
        jPanelGo = new javax.swing.JPanel();
        jPanelAvNewYork = new javax.swing.JPanel();
        jPanelAvTennesse = new javax.swing.JPanel();
        jPanelFerroPensilvania = new javax.swing.JPanel();
        jPanelArcaComunal2 = new javax.swing.JPanel();
        jPanelPlazaJames = new javax.swing.JPanel();
        jPanelAvVirginia = new javax.swing.JPanel();
        jPanelAvStatus = new javax.swing.JPanel();
        jPanelElectricidad = new javax.swing.JPanel();
        jPanelPlazaSanCarlos = new javax.swing.JPanel();
        jPanelDescanso = new javax.swing.JPanel();
        jPanelBase = new javax.swing.JPanel();
        tirarDados = new javax.swing.JButton();
        resultadoDado2 = new javax.swing.JLabel();
        revovlerDados = new javax.swing.JButton();
        resultadoDado1 = new javax.swing.JLabel();
        btnSuerte = new javax.swing.JButton();
        btnArcaComunal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanelAvKentucky = new javax.swing.JPanel();
        jPanelSuerte2 = new javax.swing.JPanel();
        jPanelAvIndiana = new javax.swing.JPanel();
        jPanelAvIllinois = new javax.swing.JPanel();
        jPanelFerroByO = new javax.swing.JPanel();
        jPanelAvAtlantico = new javax.swing.JPanel();
        jPanelAvVentnor = new javax.swing.JPanel();
        jPanelAgua = new javax.swing.JPanel();
        jPanelJardinesMarvin = new javax.swing.JPanel();
        jPanelIrACarcel = new javax.swing.JPanel();
        jPanelAvPacifico = new javax.swing.JPanel();
        jPanelAvCarolinaNorte = new javax.swing.JPanel();
        jPanelArcaComunal3 = new javax.swing.JPanel();
        jPanelAvPensilvania = new javax.swing.JPanel();
        jPanelFerroViaRapida = new javax.swing.JPanel();
        jPanelSuerte3 = new javax.swing.JPanel();
        jPanelPlazaPark = new javax.swing.JPanel();
        jPanelImpuestoLujo = new javax.swing.JPanel();
        jPanelMuelle = new javax.swing.JPanel();
        jPanelAvConnecticut = new javax.swing.JPanel();
        jPanelAvOriental = new javax.swing.JPanel();
        jPanelAvMediterraneo = new javax.swing.JPanel();
        jPanelSuerte1 = new javax.swing.JPanel();
        jPanelAvVermont = new javax.swing.JPanel();
        jPanelAvBaltica = new javax.swing.JPanel();
        jPanelFerroReading = new javax.swing.JPanel();
        jPanelArcaComunal1 = new javax.swing.JPanel();
        jPanelImpuestoIngresos = new javax.swing.JPanel();
        jTextFieldDinero1 = new javax.swing.JTextField();
        jTextFieldDinero4 = new javax.swing.JTextField();
        jTextFieldDinero2 = new javax.swing.JTextField();
        turno4 = new javax.swing.JTextField();
        jTextFieldDinero3 = new javax.swing.JTextField();
        turno1 = new javax.swing.JTextField();
        turno2 = new javax.swing.JTextField();
        turno3 = new javax.swing.JTextField();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jLabelJugador3 = new javax.swing.JLabel();
        jLabelJugador4 = new javax.swing.JLabel();
        panelTarjeta = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextRenta = new javax.swing.JTextField();
        jTextRentaDosCasas = new javax.swing.JTextField();
        jTextRentaUnaCasa = new javax.swing.JTextField();
        jTextRentaGC = new javax.swing.JTextField();
        jTextRentaCuatroCasas = new javax.swing.JTextField();
        jTextRentaTresCasas = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextRentaConHotel = new javax.swing.JTextField();
        panelJugador = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextRentaDosCasas2 = new javax.swing.JTextField();
        jTextRentaCuatroCasas2 = new javax.swing.JTextField();
        jTextRentaTresCasas2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJuego.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        panelJuego.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 20, 20));

        jPanelCarcel.setBackground(new java.awt.Color(0, 204, 204));
        jPanelCarcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelCarcelLayout = new javax.swing.GroupLayout(jPanelCarcel);
        jPanelCarcel.setLayout(jPanelCarcelLayout);
        jPanelCarcelLayout.setHorizontalGroup(
            jPanelCarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelCarcelLayout.setVerticalGroup(
            jPanelCarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelCarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 80, 80));

        jPanelGo.setBackground(new java.awt.Color(0, 204, 204));
        jPanelGo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelGoLayout = new javax.swing.GroupLayout(jPanelGo);
        jPanelGo.setLayout(jPanelGoLayout);
        jPanelGoLayout.setHorizontalGroup(
            jPanelGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelGoLayout.setVerticalGroup(
            jPanelGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 630, 80, 80));

        jPanelAvNewYork.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvNewYork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvNewYorkLayout = new javax.swing.GroupLayout(jPanelAvNewYork);
        jPanelAvNewYork.setLayout(jPanelAvNewYorkLayout);
        jPanelAvNewYorkLayout.setHorizontalGroup(
            jPanelAvNewYorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvNewYorkLayout.setVerticalGroup(
            jPanelAvNewYorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvNewYork, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 60));

        jPanelAvTennesse.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvTennesse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvTennesseLayout = new javax.swing.GroupLayout(jPanelAvTennesse);
        jPanelAvTennesse.setLayout(jPanelAvTennesseLayout);
        jPanelAvTennesseLayout.setHorizontalGroup(
            jPanelAvTennesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvTennesseLayout.setVerticalGroup(
            jPanelAvTennesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvTennesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, 60));

        jPanelFerroPensilvania.setBackground(new java.awt.Color(0, 204, 204));
        jPanelFerroPensilvania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelFerroPensilvaniaLayout = new javax.swing.GroupLayout(jPanelFerroPensilvania);
        jPanelFerroPensilvania.setLayout(jPanelFerroPensilvaniaLayout);
        jPanelFerroPensilvaniaLayout.setHorizontalGroup(
            jPanelFerroPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelFerroPensilvaniaLayout.setVerticalGroup(
            jPanelFerroPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelFerroPensilvania, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 80, 60));

        jPanelArcaComunal2.setBackground(new java.awt.Color(0, 204, 204));
        jPanelArcaComunal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelArcaComunal2Layout = new javax.swing.GroupLayout(jPanelArcaComunal2);
        jPanelArcaComunal2.setLayout(jPanelArcaComunal2Layout);
        jPanelArcaComunal2Layout.setHorizontalGroup(
            jPanelArcaComunal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelArcaComunal2Layout.setVerticalGroup(
            jPanelArcaComunal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelArcaComunal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 80, 60));

        jPanelPlazaJames.setBackground(new java.awt.Color(0, 204, 204));
        jPanelPlazaJames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaJamesLayout = new javax.swing.GroupLayout(jPanelPlazaJames);
        jPanelPlazaJames.setLayout(jPanelPlazaJamesLayout);
        jPanelPlazaJamesLayout.setHorizontalGroup(
            jPanelPlazaJamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaJamesLayout.setVerticalGroup(
            jPanelPlazaJamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaJames, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, 60));

        jPanelAvVirginia.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvVirginia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVirginiaLayout = new javax.swing.GroupLayout(jPanelAvVirginia);
        jPanelAvVirginia.setLayout(jPanelAvVirginiaLayout);
        jPanelAvVirginiaLayout.setHorizontalGroup(
            jPanelAvVirginiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvVirginiaLayout.setVerticalGroup(
            jPanelAvVirginiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVirginia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 80, 60));

        jPanelAvStatus.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvStatusLayout = new javax.swing.GroupLayout(jPanelAvStatus);
        jPanelAvStatus.setLayout(jPanelAvStatusLayout);
        jPanelAvStatusLayout.setHorizontalGroup(
            jPanelAvStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvStatusLayout.setVerticalGroup(
            jPanelAvStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 80, 60));

        jPanelElectricidad.setBackground(new java.awt.Color(0, 204, 204));
        jPanelElectricidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelElectricidadLayout = new javax.swing.GroupLayout(jPanelElectricidad);
        jPanelElectricidad.setLayout(jPanelElectricidadLayout);
        jPanelElectricidadLayout.setHorizontalGroup(
            jPanelElectricidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelElectricidadLayout.setVerticalGroup(
            jPanelElectricidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelElectricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 80, 60));

        jPanelPlazaSanCarlos.setBackground(new java.awt.Color(0, 204, 204));
        jPanelPlazaSanCarlos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaSanCarlosLayout = new javax.swing.GroupLayout(jPanelPlazaSanCarlos);
        jPanelPlazaSanCarlos.setLayout(jPanelPlazaSanCarlosLayout);
        jPanelPlazaSanCarlosLayout.setHorizontalGroup(
            jPanelPlazaSanCarlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaSanCarlosLayout.setVerticalGroup(
            jPanelPlazaSanCarlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaSanCarlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 80, 60));

        jPanelDescanso.setBackground(new java.awt.Color(0, 204, 204));
        jPanelDescanso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelDescansoLayout = new javax.swing.GroupLayout(jPanelDescanso);
        jPanelDescanso.setLayout(jPanelDescansoLayout);
        jPanelDescansoLayout.setHorizontalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelDescansoLayout.setVerticalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 80));

        jPanelBase.setBackground(new java.awt.Color(242, 249, 249));
        jPanelBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBase.setPreferredSize(new java.awt.Dimension(555, 540));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tirarDados.setText("TIRAR DADOS");
        tirarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirarDadosActionPerformed(evt);
            }
        });
        jPanelBase.add(tirarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        resultadoDado2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jPanelBase.add(resultadoDado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, 70));

        revovlerDados.setText("Revolver");
        revovlerDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revovlerDadosActionPerformed(evt);
            }
        });
        jPanelBase.add(revovlerDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, 20));

        resultadoDado1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jPanelBase.add(resultadoDado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 80, 70));

        btnSuerte.setBackground(new java.awt.Color(255, 153, 0));
        btnSuerte.setFont(new java.awt.Font("Shonar Bangla", 0, 24)); // NOI18N
        btnSuerte.setText("SUERTE");
        btnSuerte.setEnabled(false);
        btnSuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuerteActionPerformed(evt);
            }
        });
        jPanelBase.add(btnSuerte, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 260, 100));

        btnArcaComunal.setBackground(new java.awt.Color(255, 255, 105));
        btnArcaComunal.setFont(new java.awt.Font("Shonar Bangla", 0, 24)); // NOI18N
        btnArcaComunal.setText("ARCA COMUNAL");
        btnArcaComunal.setEnabled(false);
        btnArcaComunal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcaComunalActionPerformed(evt);
            }
        });
        jPanelBase.add(btnArcaComunal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 100));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("VIRTUAL MONOPOLY");
        jPanelBase.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 430, 50));

        panelJuego.add(jPanelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 554, 540));

        jPanelAvKentucky.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvKentucky.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvKentuckyLayout = new javax.swing.GroupLayout(jPanelAvKentucky);
        jPanelAvKentucky.setLayout(jPanelAvKentuckyLayout);
        jPanelAvKentuckyLayout.setHorizontalGroup(
            jPanelAvKentuckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelAvKentuckyLayout.setVerticalGroup(
            jPanelAvKentuckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvKentucky, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 80));

        jPanelSuerte2.setBackground(new java.awt.Color(0, 204, 204));
        jPanelSuerte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte2Layout = new javax.swing.GroupLayout(jPanelSuerte2);
        jPanelSuerte2.setLayout(jPanelSuerte2Layout);
        jPanelSuerte2Layout.setHorizontalGroup(
            jPanelSuerte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelSuerte2Layout.setVerticalGroup(
            jPanelSuerte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 80));

        jPanelAvIndiana.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvIndiana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvIndianaLayout = new javax.swing.GroupLayout(jPanelAvIndiana);
        jPanelAvIndiana.setLayout(jPanelAvIndianaLayout);
        jPanelAvIndianaLayout.setHorizontalGroup(
            jPanelAvIndianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvIndianaLayout.setVerticalGroup(
            jPanelAvIndianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvIndiana, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 10, -1, 80));

        jPanelAvIllinois.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvIllinois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvIllinoisLayout = new javax.swing.GroupLayout(jPanelAvIllinois);
        jPanelAvIllinois.setLayout(jPanelAvIllinoisLayout);
        jPanelAvIllinoisLayout.setHorizontalGroup(
            jPanelAvIllinoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvIllinoisLayout.setVerticalGroup(
            jPanelAvIllinoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvIllinois, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 10, -1, 80));

        jPanelFerroByO.setBackground(new java.awt.Color(0, 204, 204));
        jPanelFerroByO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelFerroByOLayout = new javax.swing.GroupLayout(jPanelFerroByO);
        jPanelFerroByO.setLayout(jPanelFerroByOLayout);
        jPanelFerroByOLayout.setHorizontalGroup(
            jPanelFerroByOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelFerroByOLayout.setVerticalGroup(
            jPanelFerroByOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelFerroByO, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 10, -1, 80));

        jPanelAvAtlantico.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvAtlantico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvAtlanticoLayout = new javax.swing.GroupLayout(jPanelAvAtlantico);
        jPanelAvAtlantico.setLayout(jPanelAvAtlanticoLayout);
        jPanelAvAtlanticoLayout.setHorizontalGroup(
            jPanelAvAtlanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvAtlanticoLayout.setVerticalGroup(
            jPanelAvAtlanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvAtlantico, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 10, -1, 80));

        jPanelAvVentnor.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvVentnor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVentnorLayout = new javax.swing.GroupLayout(jPanelAvVentnor);
        jPanelAvVentnor.setLayout(jPanelAvVentnorLayout);
        jPanelAvVentnorLayout.setHorizontalGroup(
            jPanelAvVentnorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvVentnorLayout.setVerticalGroup(
            jPanelAvVentnorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVentnor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 80));

        jPanelAgua.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAguaLayout = new javax.swing.GroupLayout(jPanelAgua);
        jPanelAgua.setLayout(jPanelAguaLayout);
        jPanelAguaLayout.setHorizontalGroup(
            jPanelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAguaLayout.setVerticalGroup(
            jPanelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 10, -1, 80));

        jPanelJardinesMarvin.setBackground(new java.awt.Color(0, 204, 204));
        jPanelJardinesMarvin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelJardinesMarvinLayout = new javax.swing.GroupLayout(jPanelJardinesMarvin);
        jPanelJardinesMarvin.setLayout(jPanelJardinesMarvinLayout);
        jPanelJardinesMarvinLayout.setHorizontalGroup(
            jPanelJardinesMarvinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelJardinesMarvinLayout.setVerticalGroup(
            jPanelJardinesMarvinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelJardinesMarvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 10, -1, 80));

        jPanelIrACarcel.setBackground(new java.awt.Color(0, 204, 204));
        jPanelIrACarcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelIrACarcelLayout = new javax.swing.GroupLayout(jPanelIrACarcel);
        jPanelIrACarcel.setLayout(jPanelIrACarcelLayout);
        jPanelIrACarcelLayout.setHorizontalGroup(
            jPanelIrACarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelIrACarcelLayout.setVerticalGroup(
            jPanelIrACarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelIrACarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 10, 80, 80));

        jPanelAvPacifico.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvPacifico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvPacificoLayout = new javax.swing.GroupLayout(jPanelAvPacifico);
        jPanelAvPacifico.setLayout(jPanelAvPacificoLayout);
        jPanelAvPacificoLayout.setHorizontalGroup(
            jPanelAvPacificoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvPacificoLayout.setVerticalGroup(
            jPanelAvPacificoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvPacifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 90, 80, 60));

        jPanelAvCarolinaNorte.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvCarolinaNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvCarolinaNorteLayout = new javax.swing.GroupLayout(jPanelAvCarolinaNorte);
        jPanelAvCarolinaNorte.setLayout(jPanelAvCarolinaNorteLayout);
        jPanelAvCarolinaNorteLayout.setHorizontalGroup(
            jPanelAvCarolinaNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvCarolinaNorteLayout.setVerticalGroup(
            jPanelAvCarolinaNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvCarolinaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 150, 80, 60));

        jPanelArcaComunal3.setBackground(new java.awt.Color(0, 204, 204));
        jPanelArcaComunal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelArcaComunal3Layout = new javax.swing.GroupLayout(jPanelArcaComunal3);
        jPanelArcaComunal3.setLayout(jPanelArcaComunal3Layout);
        jPanelArcaComunal3Layout.setHorizontalGroup(
            jPanelArcaComunal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelArcaComunal3Layout.setVerticalGroup(
            jPanelArcaComunal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelArcaComunal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 210, 80, 60));

        jPanelAvPensilvania.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvPensilvania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvPensilvaniaLayout = new javax.swing.GroupLayout(jPanelAvPensilvania);
        jPanelAvPensilvania.setLayout(jPanelAvPensilvaniaLayout);
        jPanelAvPensilvaniaLayout.setHorizontalGroup(
            jPanelAvPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvPensilvaniaLayout.setVerticalGroup(
            jPanelAvPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvPensilvania, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 270, 80, 60));

        jPanelFerroViaRapida.setBackground(new java.awt.Color(0, 204, 204));
        jPanelFerroViaRapida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFerroViaRapida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelFerroViaRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 330, 80, 60));

        jPanelSuerte3.setBackground(new java.awt.Color(0, 204, 204));
        jPanelSuerte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte3Layout = new javax.swing.GroupLayout(jPanelSuerte3);
        jPanelSuerte3.setLayout(jPanelSuerte3Layout);
        jPanelSuerte3Layout.setHorizontalGroup(
            jPanelSuerte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelSuerte3Layout.setVerticalGroup(
            jPanelSuerte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 390, 80, 60));

        jPanelPlazaPark.setBackground(new java.awt.Color(0, 204, 204));
        jPanelPlazaPark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaParkLayout = new javax.swing.GroupLayout(jPanelPlazaPark);
        jPanelPlazaPark.setLayout(jPanelPlazaParkLayout);
        jPanelPlazaParkLayout.setHorizontalGroup(
            jPanelPlazaParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaParkLayout.setVerticalGroup(
            jPanelPlazaParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaPark, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 450, 80, 60));

        jPanelImpuestoLujo.setBackground(new java.awt.Color(0, 204, 204));
        jPanelImpuestoLujo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelImpuestoLujoLayout = new javax.swing.GroupLayout(jPanelImpuestoLujo);
        jPanelImpuestoLujo.setLayout(jPanelImpuestoLujoLayout);
        jPanelImpuestoLujoLayout.setHorizontalGroup(
            jPanelImpuestoLujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelImpuestoLujoLayout.setVerticalGroup(
            jPanelImpuestoLujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelImpuestoLujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 510, 80, 60));

        jPanelMuelle.setBackground(new java.awt.Color(0, 204, 204));
        jPanelMuelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelMuelleLayout = new javax.swing.GroupLayout(jPanelMuelle);
        jPanelMuelle.setLayout(jPanelMuelleLayout);
        jPanelMuelleLayout.setHorizontalGroup(
            jPanelMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelMuelleLayout.setVerticalGroup(
            jPanelMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelMuelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 570, 80, 60));

        jPanelAvConnecticut.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvConnecticut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvConnecticutLayout = new javax.swing.GroupLayout(jPanelAvConnecticut);
        jPanelAvConnecticut.setLayout(jPanelAvConnecticutLayout);
        jPanelAvConnecticutLayout.setHorizontalGroup(
            jPanelAvConnecticutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelAvConnecticutLayout.setVerticalGroup(
            jPanelAvConnecticutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvConnecticut, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, -1, -1));

        jPanelAvOriental.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvOriental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvOriental.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelAvOriental, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 630, 62, 80));

        jPanelAvMediterraneo.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvMediterraneo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvMediterraneo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelAvMediterraneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 630, 62, 80));

        jPanelSuerte1.setBackground(new java.awt.Color(0, 204, 204));
        jPanelSuerte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte1Layout = new javax.swing.GroupLayout(jPanelSuerte1);
        jPanelSuerte1.setLayout(jPanelSuerte1Layout);
        jPanelSuerte1Layout.setHorizontalGroup(
            jPanelSuerte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelSuerte1Layout.setVerticalGroup(
            jPanelSuerte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 630, -1, -1));

        jPanelAvVermont.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvVermont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVermontLayout = new javax.swing.GroupLayout(jPanelAvVermont);
        jPanelAvVermont.setLayout(jPanelAvVermontLayout);
        jPanelAvVermontLayout.setHorizontalGroup(
            jPanelAvVermontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvVermontLayout.setVerticalGroup(
            jPanelAvVermontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVermont, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, 80));

        jPanelAvBaltica.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAvBaltica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvBaltica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelAvBaltica, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 62, 80));

        jPanelFerroReading.setBackground(new java.awt.Color(0, 204, 204));
        jPanelFerroReading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFerroReading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelFerroReading, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 630, 62, 80));

        jPanelArcaComunal1.setBackground(new java.awt.Color(0, 204, 204));
        jPanelArcaComunal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelArcaComunal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelArcaComunal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 630, 60, 80));

        jPanelImpuestoIngresos.setBackground(new java.awt.Color(0, 204, 204));
        jPanelImpuestoIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelImpuestoIngresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelImpuestoIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 630, 62, 80));

        jTextFieldDinero1.setEditable(false);
        jTextFieldDinero1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDinero1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextFieldDinero1.setText("1500");
        panelJuego.add(jTextFieldDinero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 80, 30));

        jTextFieldDinero4.setEditable(false);
        jTextFieldDinero4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDinero4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextFieldDinero4.setText("1500");
        panelJuego.add(jTextFieldDinero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 80, 30));

        jTextFieldDinero2.setEditable(false);
        jTextFieldDinero2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDinero2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextFieldDinero2.setText("1500");
        panelJuego.add(jTextFieldDinero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 80, 30));

        turno4.setEditable(false);
        turno4.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.add(turno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 40, 50));

        jTextFieldDinero3.setEditable(false);
        jTextFieldDinero3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDinero3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextFieldDinero3.setText("1500");
        panelJuego.add(jTextFieldDinero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 80, 30));

        turno1.setEditable(false);
        turno1.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.add(turno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 40, 50));

        turno2.setEditable(false);
        turno2.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.add(turno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 40, 50));

        turno3.setEditable(false);
        turno3.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.add(turno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 40, 50));

        jLabelJugador1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabelJugador1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelJugador1.setText("JUGADOR ");
        jLabelJugador1.setToolTipText("");
        jLabelJugador1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        jLabelJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugador1MouseClicked(evt);
            }
        });
        panelJuego.add(jLabelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 70));

        jLabelJugador2.setBackground(new java.awt.Color(255, 204, 0));
        jLabelJugador2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelJugador2.setForeground(new java.awt.Color(255, 204, 0));
        jLabelJugador2.setText("JUGADOR ");
        jLabelJugador2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 5));
        panelJuego.add(jLabelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 150, 70));

        jLabelJugador3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelJugador3.setForeground(new java.awt.Color(102, 204, 0));
        jLabelJugador3.setText("JUGADOR ");
        jLabelJugador3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 0), 5, true));
        panelJuego.add(jLabelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 150, 70));

        jLabelJugador4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelJugador4.setForeground(new java.awt.Color(102, 0, 204));
        jLabelJugador4.setText("JUGADOR");
        jLabelJugador4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 5));
        panelJuego.add(jLabelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 150, 70));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel33.setText("jLabel33");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setText("Renta");

        jLabel2.setText("Renta grupo de Color");

        jLabel3.setText("Renta con 1 casa");

        jLabel4.setText("Renta con 2 casas");

        jLabel5.setText("Renta con 3 casas");

        jLabel9.setText("Renta con 4 casas");

        jLabel10.setText("Renta con 1 hotel ");

        jLabel11.setText("Costo por casa");

        jLabel13.setText("Costo por Hote (con 4 casas)");
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout panelTarjetaLayout = new javax.swing.GroupLayout(panelTarjeta);
        panelTarjeta.setLayout(panelTarjetaLayout);
        panelTarjetaLayout.setHorizontalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaConHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaCuatroCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaTresCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaDosCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRentaUnaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTarjetaLayout.setVerticalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextRentaGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextRentaUnaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextRentaDosCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextRentaTresCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextRentaCuatroCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextRentaConHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        panelJuego.add(panelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 270, 440));

        panelJugador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("PARTICIPAR EN SUBASTA");
        jButton5.setEnabled(false);
        panelJugador.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, -1));

        jButton6.setText("SALIR JUEGO");
        jButton6.setEnabled(false);
        panelJugador.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 250, -1));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelJugador.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        jLabel24.setText("Propiedades");
        panelJugador.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        jLabel27.setText("Cantidad casas");
        panelJugador.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel28.setText("Cantidad hoteles");
        panelJugador.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel29.setText("Carta carcel");
        panelJugador.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel30.setText("Propiedades Hipotecadas ");
        panelJugador.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jTextRentaDosCasas2.setEditable(false);
        panelJugador.add(jTextRentaDosCasas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        jTextRentaCuatroCasas2.setEditable(false);
        panelJugador.add(jTextRentaCuatroCasas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 110, -1));

        jTextRentaTresCasas2.setEditable(false);
        panelJugador.add(jTextRentaTresCasas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelJugador.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, 70));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        panelJugador.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 70));

        jButton7.setText("VENDER CARTA \"SALIR CARCEL\"");
        jButton7.setEnabled(false);
        panelJugador.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, -1));

        jButton8.setText("ENTREGAR ADQUISIONES");
        jButton8.setEnabled(false);
        panelJugador.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, -1));

        panelJuego.add(panelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, 530));

        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    
    private void tirarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirarDadosActionPerformed

       // if(seleccion){
            ClassJugador memo = (ClassJugador) jugadores.desencolar();
            memo.avanzar(casillas);
            jugadores.encolar(memo);
           
              
            ValidarCasillaComunalSuerte();
        /*}

       // }

        
      /*  else{
            ClassJugador memo2 = (ClassJugador) jugadores.desencolar();
            if(memo2!=null){
                 memo2.tirarDado();
                 return;
            }
            
            this.seleccion = false;
            this.jugadores = new Cola();

            switch (formInicio.message){
            
                case "2":
                   
                    if(jugador1.getTiro()>jugador2.getTiro()){
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador2);
                    }else
                    if(jugador1.getTiro()==jugador2.getTiro()){
                        
                    }
                    else{
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                    }
                break; 
                
                 case "3":
                     if(jugador1.getTiro()>jugador2.getTiro()&&jugador1.getTiro()>jugador3.getTiro()&&jugador2.getTiro()>jugador3.getTiro()){
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador3);
                    }else
                      if(jugador2.getTiro()>jugador1.getTiro()&&jugador2.getTiro()>jugador3.getTiro()&&jugador1.getTiro()>jugador3.getTiro()){
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador1);
                    }
                      else{
                        jugadores.encolar(jugador3);
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                      }
                break;
                
                 case "4":
                     if(jugador1.getTiro()>jugador2.getTiro()&&jugador1.getTiro()>jugador3.getTiro()&&jugador1.getTiro()>jugador4.getTiro()&&
                             jugador2.getTiro()>jugador3.getTiro()&&jugador2.getTiro()>jugador4.getTiro()&&jugador3.getTiro()>jugador4.getTiro()){
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador3);
                        jugadores.encolar(jugador4);
                    }else
                      if(jugador2.getTiro()>jugador1.getTiro()&&jugador2.getTiro()>jugador3.getTiro()&&jugador2.getTiro()>jugador4.getTiro()&&
                             jugador1.getTiro()>jugador3.getTiro()&&jugador1.getTiro()>jugador4.getTiro()&&jugador3.getTiro()>jugador4.getTiro()){
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador3);
                        jugadores.encolar(jugador3);
                    }else
                      if(jugador3.getTiro()>jugador1.getTiro()&&jugador3.getTiro()>jugador2.getTiro()&&jugador3.getTiro()>jugador4.getTiro()&&
                             jugador1.getTiro()>jugador2.getTiro()&&jugador1.getTiro()>jugador4.getTiro()&&jugador2.getTiro()>jugador4.getTiro()){
                        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador3);
                        jugadores.encolar(jugador3);
                    }
                     
                break;

        }
        }*/
    }//GEN-LAST:event_tirarDadosActionPerformed

     public void ValidarCasillaComunalSuerte(){ 
             
        if(jugador1.getPosicion()==8||jugador1.getPosicion()==23||jugador1.getPosicion()==37){
            btnSuerte.setEnabled(true);
        }
        
        if(jugador1.getPosicion()==3||jugador1.getPosicion()==18||jugador1.getPosicion()==34){
            btnArcaComunal.setEnabled(true);
        }
    }

     
    
    public void asignarCarta(){
    
        Object salirCarcel = JOptionPane.showConfirmDialog(null,"Salir de la carcel");
        Object honoMedicos = JOptionPane.showConfirmDialog(null,"Honorarios médicos, pague $50");
        Object vencimientoFondo = JOptionPane.showConfirmDialog(null,"Vencimiento de fondo vacacional, reciba $100");
        Object vencimientoSeguro = JOptionPane.showConfirmDialog(null,"Vencimiento de seguro de vida, Cobre $100. ");
        Object pagoCole = JOptionPane.showConfirmDialog(null,"Pague colegiaturas por $50");
        Object devolucionIm = JOptionPane.showConfirmDialog(null,"Devolución de impuestos. Cobre $20");
        Object hospital = JOptionPane.showConfirmDialog(null,"Pague cuenta de hospital por $100");
        Object irCarcel = JOptionPane.showConfirmDialog(null,"Váyase a la CÁRCEL. No pase por la SALIDA, no cobra $200.");
        Object consultoria = JOptionPane.showConfirmDialog(null,"Reciba $25 por consultoría");
        Object cumple = JOptionPane.showConfirmDialog(null,"Es su cumpleaños. Cobre $10 a cada jugador");
        Object heredar = JOptionPane.showConfirmDialog(null,"Herede $100");
        Object acciones = JOptionPane.showConfirmDialog(null,"Por venta de acciones reciba $50");
        Object concurso = JOptionPane.showConfirmDialog(null,"Ganó el segundo lugar en un concurso de belleza, cobre $10");
        Object reparacion = JOptionPane.showConfirmDialog(null,"Por reparación vial le cobran: $40 por casa, $115 por hotel");
        Object avanzar = JOptionPane.showConfirmDialog(null,"Avance a la SALIDA, cobre $200");
        Object error = JOptionPane.showConfirmDialog(null,"Error bancario a su favor. Cobre $200.");
        
        comunal.apilar(salirCarcel);
        comunal.apilar(honoMedicos);
        comunal.apilar(vencimientoFondo);
        comunal.apilar(vencimientoSeguro);
        comunal.apilar(pagoCole);
        comunal.apilar(devolucionIm);
        comunal.apilar(hospital);
        comunal.apilar(irCarcel);
        comunal.apilar(consultoria);
        comunal.apilar(cumple);
        comunal.apilar(heredar);
        comunal.apilar(acciones);
        comunal.apilar(concurso);
        comunal.apilar(reparacion);
        comunal.apilar(avanzar);
        comunal.apilar(error);
        
        Object muelle = JOptionPane.showConfirmDialog(null,"Avance a EL MUELLE.");
        Object reading = JOptionPane.showConfirmDialog(null,"Viaje en el Ferrocarril READING, si pasa por “SALIDA” cobre $200");
        Object cumplimiento = JOptionPane.showConfirmDialog(null,"Por cumplimiento en pago del préstamo de construcción cobre $150");
        Object illinois = JOptionPane.showConfirmDialog(null,"Avance a AVENIDA ILLINOIS. Si pasa por la salida cobre $200.");
        Object servicio= JOptionPane.showConfirmDialog(null,"AVANCE AL SERVICIO MÁS CERCANO. Si está a LA VENTA, puede comprárselo al banco. Si es PROPIEDAD de alguien, tira los dados y pague 10 veces lo pagado.");
        Object irCarcelS= JOptionPane.showConfirmDialog(null,"Váyase a la CÁRCEL. No pase por la SALIDA, no cobra $200");
        Object salida= JOptionPane.showConfirmDialog(null,"Avance a la SALIDA, cobre $200.");
        Object dividendo = JOptionPane.showConfirmDialog(null,"El banco le paga dividendos por $50.");
        Object reparacionS = JOptionPane.showConfirmDialog(null,"Haga reparaciones en sus propiedades; por cada casa pague $25, por cada hotel pague $100");
        Object salirCarcelS = JOptionPane.showConfirmDialog(null,"Salir de la carcel");
        Object presidente = JOptionPane.showConfirmDialog(null,"Ha sido elegido presidente del concejo de administración. Pague a cada jugador $50");
        Object velocidad= JOptionPane.showConfirmDialog(null,"Pague multa por exceso de velocidad $15");
        Object ferro= JOptionPane.showConfirmDialog(null,"Avance al ferrocarril más cercano");
        Object jardin = JOptionPane.showConfirmDialog(null,"Avance a Jardines Marvin");
        
        comunal.apilar(muelle);
        comunal.apilar(reading);
        comunal.apilar(cumplimiento);
        comunal.apilar(illinois);
        comunal.apilar(servicio);
        comunal.apilar(irCarcelS);
        comunal.apilar(salida);
        comunal.apilar(dividendo);
        comunal.apilar(reparacionS);
        comunal.apilar(salirCarcelS);
        comunal.apilar(presidente);
        comunal.apilar(velocidad);
        comunal.apilar(ferro);
        comunal.apilar(jardin);
        comunal.apilar(avanzar);
        comunal.apilar(error);
 
    
} 
    private void jLabelJugador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugador1MouseClicked
       
    }//GEN-LAST:event_jLabelJugador1MouseClicked

    private void revovlerDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revovlerDadosActionPerformed
        ClassDados insertGif = new ClassDados();
        resultadoDado1.setIcon(insertGif.gifDado1());
        resultadoDado2.setIcon(insertGif.gifDado2());
    }//GEN-LAST:event_revovlerDadosActionPerformed

    private void btnSuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuerteActionPerformed
        btnSuerte.setEnabled(false);
    }//GEN-LAST:event_btnSuerteActionPerformed

    private void btnArcaComunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcaComunalActionPerformed
        btnArcaComunal.setEnabled(false);
        //comunal.cima();
       
    }//GEN-LAST:event_btnArcaComunalActionPerformed


        
    
    public void asignar(){
        casillas.add(jPanelGo);
        casillas.add(jPanelAvMediterraneo);
        casillas.add(jPanelArcaComunal1);
        casillas.add(jPanelAvBaltica);
        casillas.add(jPanelImpuestoIngresos);
        casillas.add(jPanelFerroReading);
        casillas.add(jPanelAvOriental);
        casillas.add(jPanelSuerte1);
        casillas.add(jPanelAvVermont);
        casillas.add(jPanelAvConnecticut);
        casillas.add(jPanelCarcel);
        casillas.add(jPanelPlazaSanCarlos);
        casillas.add(jPanelElectricidad);
        casillas.add(jPanelAvStatus);
        casillas.add(jPanelAvVirginia);
        casillas.add(jPanelFerroPensilvania);
        casillas.add(jPanelPlazaJames);
        casillas.add(jPanelArcaComunal2);
        casillas.add(jPanelAvTennesse);
        casillas.add(jPanelAvNewYork);
        casillas.add(jPanelDescanso);
        casillas.add(jPanelAvKentucky);
        casillas.add(jPanelSuerte2);
        casillas.add(jPanelAvIndiana);
        casillas.add(jPanelAvIllinois);
        casillas.add(jPanelFerroByO);
        casillas.add(jPanelAvAtlantico);
        casillas.add(jPanelAvVentnor);
        casillas.add(jPanelAgua);
        casillas.add(jPanelJardinesMarvin);
        casillas.add(jPanelIrACarcel);
        casillas.add(jPanelAvPacifico);
        casillas.add(jPanelAvCarolinaNorte);
        casillas.add(jPanelArcaComunal3);
        casillas.add(jPanelAvPensilvania);
        casillas.add(jPanelFerroViaRapida);
        casillas.add(jPanelSuerte3);
        casillas.add(jPanelPlazaPark);
        casillas.add(jPanelImpuestoLujo);
        casillas.add(jPanelMuelle); 
        jugadores.encolar(jugador2);
                        jugadores.encolar(jugador1);
                        jugadores.encolar(jugador3);
                        jugadores.encolar(jugador4);
   
        
    }
    
   
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JButton btnArcaComunal;
    private javax.swing.JButton btnSuerte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    public static javax.swing.JLabel jLabelJugador3;
    protected static javax.swing.JLabel jLabelJugador4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAgua;
    private javax.swing.JPanel jPanelArcaComunal1;
    private javax.swing.JPanel jPanelArcaComunal2;
    private javax.swing.JPanel jPanelArcaComunal3;
    private javax.swing.JPanel jPanelAvAtlantico;
    private javax.swing.JPanel jPanelAvBaltica;
    private javax.swing.JPanel jPanelAvCarolinaNorte;
    private javax.swing.JPanel jPanelAvConnecticut;
    private javax.swing.JPanel jPanelAvIllinois;
    private javax.swing.JPanel jPanelAvIndiana;
    private javax.swing.JPanel jPanelAvKentucky;
    private javax.swing.JPanel jPanelAvMediterraneo;
    private javax.swing.JPanel jPanelAvNewYork;
    private javax.swing.JPanel jPanelAvOriental;
    private javax.swing.JPanel jPanelAvPacifico;
    private javax.swing.JPanel jPanelAvPensilvania;
    private javax.swing.JPanel jPanelAvStatus;
    private javax.swing.JPanel jPanelAvTennesse;
    private javax.swing.JPanel jPanelAvVentnor;
    private javax.swing.JPanel jPanelAvVermont;
    private javax.swing.JPanel jPanelAvVirginia;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCarcel;
    private javax.swing.JPanel jPanelDescanso;
    private javax.swing.JPanel jPanelElectricidad;
    private javax.swing.JPanel jPanelFerroByO;
    private javax.swing.JPanel jPanelFerroPensilvania;
    private javax.swing.JPanel jPanelFerroReading;
    private javax.swing.JPanel jPanelFerroViaRapida;
    private javax.swing.JPanel jPanelGo;
    private javax.swing.JPanel jPanelImpuestoIngresos;
    private javax.swing.JPanel jPanelImpuestoLujo;
    private javax.swing.JPanel jPanelIrACarcel;
    private javax.swing.JPanel jPanelJardinesMarvin;
    private javax.swing.JPanel jPanelMuelle;
    private javax.swing.JPanel jPanelPlazaJames;
    private javax.swing.JPanel jPanelPlazaPark;
    private javax.swing.JPanel jPanelPlazaSanCarlos;
    private javax.swing.JPanel jPanelSuerte1;
    private javax.swing.JPanel jPanelSuerte2;
    private javax.swing.JPanel jPanelSuerte3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField jTextFieldDinero1;
    public static javax.swing.JTextField jTextFieldDinero2;
    public static javax.swing.JTextField jTextFieldDinero3;
    public static javax.swing.JTextField jTextFieldDinero4;
    private javax.swing.JTextField jTextRenta;
    private javax.swing.JTextField jTextRentaConHotel;
    private javax.swing.JTextField jTextRentaCuatroCasas;
    private javax.swing.JTextField jTextRentaCuatroCasas2;
    private javax.swing.JTextField jTextRentaDosCasas;
    private javax.swing.JTextField jTextRentaDosCasas2;
    private javax.swing.JTextField jTextRentaGC;
    private javax.swing.JTextField jTextRentaTresCasas;
    private javax.swing.JTextField jTextRentaTresCasas2;
    private javax.swing.JTextField jTextRentaUnaCasa;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelJugador;
    private javax.swing.JPanel panelTarjeta;
    public static javax.swing.JLabel resultadoDado1;
    public static javax.swing.JLabel resultadoDado2;
    private javax.swing.JButton revovlerDados;
    private javax.swing.JButton tirarDados;
    public static javax.swing.JTextField turno1;
    public static javax.swing.JTextField turno2;
    public static javax.swing.JTextField turno3;
    public static javax.swing.JTextField turno4;
    // End of variables declaration//GEN-END:variables
}
